name: Build do projeto .NET

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # roda de hora em hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do projeto
        uses: actions/checkout@v4

      - name: Instalar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar pacotes do projeto
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --configuration Release
